START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE content_hashes (
        id uuid NOT NULL,
        hash_value character varying(64) NOT NULL,
        source_url character varying(500) NOT NULL,
        created_at timestamptz NOT NULL,
        CONSTRAINT "PK_content_hashes" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE "ExamOffers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(50) NOT NULL,
        "Title" character varying(120) NOT NULL,
        "Description" character varying(500),
        "OfferType" integer NOT NULL,
        "Value" numeric NOT NULL,
        "MinOrderAmount" numeric NOT NULL,
        "MaxDiscountAmount" numeric,
        "ExamPageId" uuid,
        "MaxUses" integer,
        "UsedCount" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "ValidFrom" timestamp with time zone,
        "ValidTo" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExamOffers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE exams (
        id uuid NOT NULL,
        name character varying(200) NOT NULL,
        slug character varying(220) NOT NULL,
        category character varying(100),
        level character varying(100),
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamptz NOT NULL,
        CONSTRAINT "PK_exams" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE test_questions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        test_id uuid NOT NULL,
        question_id uuid NOT NULL,
        sort_order integer NOT NULL DEFAULT 0,
        added_at timestamptz NOT NULL,
        CONSTRAINT "PK_test_questions" PRIMARY KEY (id),
        CONSTRAINT "FK_test_questions_questions_question_id" FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE,
        CONSTRAINT "FK_test_questions_tests_test_id" FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE "ExamOrders" (
        "Id" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "ExamPageId" uuid NOT NULL,
        "OriginalAmount" numeric NOT NULL,
        "DiscountAmount" numeric NOT NULL,
        "FinalAmount" numeric NOT NULL,
        "GstAmount" numeric NOT NULL,
        "GrandTotal" numeric NOT NULL,
        "OfferId" integer,
        "OfferCode" character varying(50),
        "RazorpayOrderId" character varying(100),
        "RazorpayPaymentId" character varying(100),
        "RazorpaySignature" character varying(256),
        "Status" integer NOT NULL,
        "BookingRef" character varying(30) NOT NULL,
        "FailureReason" character varying(500),
        "Notes" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "PaidAt" timestamp with time zone,
        CONSTRAINT "PK_ExamOrders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExamOrders_ExamOffers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "ExamOffers" ("Id"),
        CONSTRAINT "FK_ExamOrders_exam_pages_ExamPageId" FOREIGN KEY ("ExamPageId") REFERENCES exam_pages ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ExamOrders_users_StudentId" FOREIGN KEY ("StudentId") REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE exam_notifications (
        id uuid NOT NULL,
        exam_id uuid,
        title character varying(300) NOT NULL,
        slug character varying(320) NOT NULL,
        content_html text NOT NULL,
        summary character varying(500),
        notification_type integer NOT NULL,
        important_dates jsonb,
        source_url character varying(500) NOT NULL,
        canonical_url character varying(500),
        meta_title character varying(300),
        meta_description character varying(500),
        published_at timestamptz,
        is_ai_processed boolean NOT NULL DEFAULT FALSE,
        ai_processed_at timestamptz,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        status integer NOT NULL DEFAULT 0,
        CONSTRAINT "PK_exam_notifications" PRIMARY KEY (id),
        CONSTRAINT "FK_exam_notifications_exams_exam_id" FOREIGN KEY (exam_id) REFERENCES exams (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE "ExamAccesses" (
        "Id" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "ExamPageId" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "GrantedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_ExamAccesses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExamAccesses_ExamOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "ExamOrders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ExamAccesses_exam_pages_ExamPageId" FOREIGN KEY ("ExamPageId") REFERENCES exam_pages ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ExamAccesses_users_StudentId" FOREIGN KEY ("StudentId") REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE "ExamOrderTransactions" (
        "Id" uuid NOT NULL,
        "ExamOrderId" uuid NOT NULL,
        "Event" character varying(80) NOT NULL,
        "RazorpayPaymentId" character varying(100),
        "RazorpayOrderId" character varying(100),
        "Amount" numeric,
        "RawPayload" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExamOrderTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExamOrderTransactions_ExamOrders_ExamOrderId" FOREIGN KEY ("ExamOrderId") REFERENCES "ExamOrders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE TABLE content_versions (
        id uuid NOT NULL,
        entity_type character varying(80) NOT NULL,
        entity_id uuid NOT NULL,
        content_html text NOT NULL,
        created_at timestamptz NOT NULL,
        "ExamNotificationId" uuid,
        CONSTRAINT "PK_content_versions" PRIMARY KEY (id),
        CONSTRAINT "FK_content_versions_exam_notifications_ExamNotificationId" FOREIGN KEY ("ExamNotificationId") REFERENCES exam_notifications (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE UNIQUE INDEX ix_content_hashes_hash_value ON content_hashes (hash_value);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX ix_content_versions_entity ON content_versions (entity_type, entity_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_content_versions_ExamNotificationId" ON content_versions ("ExamNotificationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX ix_exam_notifications_exam_id ON exam_notifications (exam_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX ix_exam_notifications_is_ai_processed ON exam_notifications (is_ai_processed);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX ix_exam_notifications_published_at ON exam_notifications (published_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE UNIQUE INDEX ix_exam_notifications_slug ON exam_notifications (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX ix_exam_notifications_status ON exam_notifications (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX ix_exam_notifications_type ON exam_notifications (notification_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_ExamAccesses_ExamPageId" ON "ExamAccesses" ("ExamPageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE UNIQUE INDEX "IX_ExamAccesses_OrderId" ON "ExamAccesses" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_ExamAccesses_StudentId" ON "ExamAccesses" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_ExamOrders_ExamPageId" ON "ExamOrders" ("ExamPageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_ExamOrders_OfferId" ON "ExamOrders" ("OfferId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_ExamOrders_StudentId" ON "ExamOrders" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_ExamOrderTransactions_ExamOrderId" ON "ExamOrderTransactions" ("ExamOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX ix_exams_category_level ON exams (category, level);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE UNIQUE INDEX ix_exams_slug ON exams (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_test_questions_question_id" ON test_questions (question_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    CREATE INDEX "IX_test_questions_test_id" ON test_questions (test_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412060927_AddExamPaymentModule') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260412060927_AddExamPaymentModule', '8.0.8');
    END IF;
END $EF$;
COMMIT;

