// <auto-generated />
using System;
using GridAcademy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridAcademy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321095707_AddAssessmentModule")]
    partial class AddAssessmentModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.AttemptAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<bool>("IsClear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_clear");

                    b.Property<decimal?>("NumericalValue")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("numerical_value");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.Property<string>("SelectedOptionIds")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("selected_option_ids");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_attempt_answers_attempt_question");

                    b.ToTable("attempt_answers", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.AttemptQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("DisplayOrderInSection")
                        .HasColumnType("integer")
                        .HasColumnName("display_order_in_section");

                    b.Property<bool>("IsMarkedForReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_marked_for_review");

                    b.Property<bool>("IsVisited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_visited");

                    b.Property<decimal>("MarksForCorrect")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("marks_for_correct");

                    b.Property<decimal>("NegativeMarks")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("negative_marks");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("SectionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("section_index");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("section_name");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AttemptId", "DisplayOrder")
                        .HasDatabaseName("ix_attempt_questions_attempt_order");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_attempt_questions_attempt_question");

                    b.ToTable("attempt_questions", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.AttemptSectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<int>("Attempted")
                        .HasColumnType("integer")
                        .HasColumnName("attempted");

                    b.Property<int>("Correct")
                        .HasColumnType("integer")
                        .HasColumnName("correct");

                    b.Property<int>("Incorrect")
                        .HasColumnType("integer")
                        .HasColumnName("incorrect");

                    b.Property<decimal>("MarksObtained")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("marks_obtained");

                    b.Property<decimal>("MaxMarks")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("max_marks");

                    b.Property<int>("SectionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("section_index");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("section_name");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<int>("Unattempted")
                        .HasColumnType("integer")
                        .HasColumnName("unattempted");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_attempt_section_results_attempt_id");

                    b.ToTable("attempt_section_results", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_type_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("NegativeMarkingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("negative_marking_enabled");

                    b.Property<decimal>("PassingPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("passing_percent");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ExamTypeId")
                        .HasDatabaseName("ix_tests_exam_type_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tests_status");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.TestAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime>("AvailableFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_from");

                    b.Property<DateTime>("AvailableTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_to");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("max_attempts");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_test_assignments_student_id");

                    b.HasIndex("TestId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_test_assignments_test_student");

                    b.ToTable("test_assignments", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.TestAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<int>("DurationSecondsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_seconds_used");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<decimal?>("TotalMarksObtained")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("total_marks_obtained");

                    b.Property<decimal?>("TotalMarksPossible")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("total_marks_possible");

                    b.Property<string>("ViolationLog")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("violation_log");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_test_attempts_status");

                    b.HasIndex("AssignmentId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_test_attempts_assignment_num");

                    b.HasIndex("StudentId", "TestId")
                        .HasDatabaseName("ix_test_attempts_student_test");

                    b.ToTable("test_attempts", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.TestSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("DifficultyLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_level_id");

                    b.Property<decimal>("MarksPerQuestion")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("marks_per_question");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("NegativeMarksPerQuestion")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("negative_marks_per_question");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevelId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TestId", "SortOrder")
                        .HasDatabaseName("ix_test_sections_test_sort");

                    b.ToTable("test_sections", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.ComplexityLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("complexity_levels", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("difficulty_levels", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.ExamType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("exam_types", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.MarksMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("marks_master", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.NegativeMarksMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("negative_marks_master", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssertionText")
                        .HasColumnType("text")
                        .HasColumnName("assertion_text");

                    b.Property<int>("ComplexityLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("complexity_level_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DifficultyLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_level_id");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_type_id");

                    b.Property<int>("MarksId")
                        .HasColumnType("integer")
                        .HasColumnName("marks_id");

                    b.Property<int>("NegativeMarksId")
                        .HasColumnType("integer")
                        .HasColumnName("negative_marks_id");

                    b.Property<decimal?>("NumericalAnswer")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("numerical_answer");

                    b.Property<decimal?>("NumericalTolerance")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("numerical_tolerance");

                    b.Property<Guid?>("PassageId")
                        .HasColumnType("uuid")
                        .HasColumnName("passage_id");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("question_type_id");

                    b.Property<string>("ReasonText")
                        .HasColumnType("text")
                        .HasColumnName("reason_text");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<string>("Subtopic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subtopic");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ComplexityLevelId");

                    b.HasIndex("DifficultyLevelId")
                        .HasDatabaseName("ix_questions_difficulty_level_id");

                    b.HasIndex("ExamTypeId")
                        .HasDatabaseName("ix_questions_exam_type_id");

                    b.HasIndex("MarksId");

                    b.HasIndex("NegativeMarksId");

                    b.HasIndex("PassageId")
                        .HasDatabaseName("ix_questions_passage_id");

                    b.HasIndex("QuestionType")
                        .HasDatabaseName("ix_questions_question_type_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_questions_status");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_questions_subject_id");

                    b.HasIndex("TopicId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionBlank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateAnswers")
                        .HasColumnType("text")
                        .HasColumnName("alternate_answers");

                    b.Property<int>("BlankIndex")
                        .HasColumnType("integer")
                        .HasColumnName("blank_index");

                    b.Property<bool>("CaseSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("case_sensitive");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correct_answer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "BlankIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_question_blanks_question_blank");

                    b.ToTable("question_blanks", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionMatchCorrect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("LeftLabel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("left_label");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("RightLabel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("right_label");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "LeftLabel", "RightLabel")
                        .IsUnique()
                        .HasDatabaseName("ix_question_match_correct_unique");

                    b.ToTable("question_match_correct", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionMatchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnSide")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("column_side");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("label");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_match_items_question_id");

                    b.ToTable("question_match_items", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<char>("Label")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("label");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PassageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passage_text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("question_passages", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("QuestionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("question_tags", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_question_types_code");

                    b.ToTable("question_types", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.AttemptAnswer", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Assessment.TestAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.AttemptQuestion", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Assessment.TestAttempt", "Attempt")
                        .WithMany("Questions")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Content.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.AttemptSectionResult", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Assessment.TestAttempt", "Attempt")
                        .WithMany("SectionResults")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.Test", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.ExamType", "ExamType")
                        .WithMany()
                        .HasForeignKey("ExamTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamType");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.TestAssignment", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Assessment.Test", "Test")
                        .WithMany("Assignments")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.TestAttempt", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Assessment.TestAssignment", "Assignment")
                        .WithMany("Attempts")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.TestSection", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.DifficultyLevel", "DifficultyLevel")
                        .WithMany()
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GridAcademy.Data.Entities.Content.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Assessment.Test", "Test")
                        .WithMany("Sections")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Subject");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Question", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.ComplexityLevel", "ComplexityLevel")
                        .WithMany("Questions")
                        .HasForeignKey("ComplexityLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Content.DifficultyLevel", "DifficultyLevel")
                        .WithMany("Questions")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Content.ExamType", "ExamType")
                        .WithMany("Questions")
                        .HasForeignKey("ExamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Content.MarksMaster", "Marks")
                        .WithMany("Questions")
                        .HasForeignKey("MarksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Content.NegativeMarksMaster", "NegativeMarks")
                        .WithMany("Questions")
                        .HasForeignKey("NegativeMarksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Content.QuestionPassage", "Passage")
                        .WithMany("Questions")
                        .HasForeignKey("PassageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GridAcademy.Data.Entities.Content.QuestionTypeMaster", "QuestionTypeMaster")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_question_type_id");

                    b.HasOne("GridAcademy.Data.Entities.Content.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Content.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplexityLevel");

                    b.Navigation("DifficultyLevel");

                    b.Navigation("ExamType");

                    b.Navigation("Marks");

                    b.Navigation("NegativeMarks");

                    b.Navigation("Passage");

                    b.Navigation("QuestionTypeMaster");

                    b.Navigation("Subject");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionBlank", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.Question", "Question")
                        .WithMany("Blanks")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionMatchCorrect", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.Question", "Question")
                        .WithMany("MatchCorrect")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionMatchItem", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.Question", "Question")
                        .WithMany("MatchItems")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionOption", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionTag", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.Question", "Question")
                        .WithMany("QuestionTags")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridAcademy.Data.Entities.Content.Tag", "Tag")
                        .WithMany("QuestionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Topic", b =>
                {
                    b.HasOne("GridAcademy.Data.Entities.Content.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.Test", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.TestAssignment", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Assessment.TestAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Questions");

                    b.Navigation("SectionResults");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.ComplexityLevel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.DifficultyLevel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.ExamType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.MarksMaster", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.NegativeMarksMaster", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Question", b =>
                {
                    b.Navigation("Blanks");

                    b.Navigation("MatchCorrect");

                    b.Navigation("MatchItems");

                    b.Navigation("Options");

                    b.Navigation("QuestionTags");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionPassage", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.QuestionTypeMaster", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Subject", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Tag", b =>
                {
                    b.Navigation("QuestionTags");
                });

            modelBuilder.Entity("GridAcademy.Data.Entities.Content.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
