using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridAcademy.Migrations
{
    /// <inheritdoc />
    public partial class AddExamPaymentModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // All statements use IF NOT EXISTS so this migration is idempotent.
            // Some of these tables were partially created on Railway before the
            // migration record was inserted, causing repeated failures.

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS content_hashes (
                    id         uuid                    NOT NULL,
                    hash_value character varying(64)   NOT NULL,
                    source_url character varying(500)  NOT NULL,
                    created_at timestamptz             NOT NULL,
                    CONSTRAINT "PK_content_hashes" PRIMARY KEY (id)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ix_content_hashes_hash_value ON content_hashes (hash_value);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "ExamOffers" (
                    "Id"                integer GENERATED BY DEFAULT AS IDENTITY,
                    "Code"              character varying(50)  NOT NULL,
                    "Title"             character varying(120) NOT NULL,
                    "Description"       character varying(500),
                    "OfferType"         integer  NOT NULL DEFAULT 0,
                    "Value"             numeric  NOT NULL DEFAULT 0,
                    "MinOrderAmount"    numeric  NOT NULL DEFAULT 0,
                    "MaxDiscountAmount" numeric,
                    "ExamPageId"        uuid,
                    "MaxUses"           integer,
                    "UsedCount"         integer  NOT NULL DEFAULT 0,
                    "IsActive"          boolean  NOT NULL DEFAULT true,
                    "ValidFrom"         timestamp with time zone,
                    "ValidTo"           timestamp with time zone,
                    "CreatedAt"         timestamp with time zone NOT NULL DEFAULT now(),
                    "UpdatedAt"         timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "PK_ExamOffers" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS exams (
                    id        uuid                    NOT NULL,
                    name      character varying(200)  NOT NULL,
                    slug      character varying(220)  NOT NULL,
                    category  character varying(100),
                    level     character varying(100),
                    is_active boolean NOT NULL DEFAULT true,
                    created_at timestamptz NOT NULL,
                    CONSTRAINT "PK_exams" PRIMARY KEY (id)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ix_exams_slug          ON exams (slug);
                CREATE INDEX        IF NOT EXISTS ix_exams_category_level ON exams (category, level);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS test_questions (
                    id          integer GENERATED BY DEFAULT AS IDENTITY,
                    test_id     uuid    NOT NULL,
                    question_id uuid    NOT NULL,
                    sort_order  integer NOT NULL DEFAULT 0,
                    added_at    timestamptz NOT NULL,
                    CONSTRAINT "PK_test_questions" PRIMARY KEY (id)
                );
                CREATE INDEX IF NOT EXISTS "IX_test_questions_test_id"     ON test_questions (test_id);
                CREATE INDEX IF NOT EXISTS "IX_test_questions_question_id" ON test_questions (question_id);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "ExamOrders" (
                    "Id"                uuid    NOT NULL DEFAULT gen_random_uuid(),
                    "StudentId"         uuid    NOT NULL,
                    "ExamPageId"        uuid    NOT NULL,
                    "OriginalAmount"    numeric NOT NULL DEFAULT 0,
                    "DiscountAmount"    numeric NOT NULL DEFAULT 0,
                    "FinalAmount"       numeric NOT NULL DEFAULT 0,
                    "GstAmount"         numeric NOT NULL DEFAULT 0,
                    "GrandTotal"        numeric NOT NULL DEFAULT 0,
                    "OfferId"           integer,
                    "OfferCode"         character varying(50),
                    "RazorpayOrderId"   character varying(100),
                    "RazorpayPaymentId" character varying(100),
                    "RazorpaySignature" character varying(256),
                    "Status"            integer NOT NULL DEFAULT 0,
                    "BookingRef"        character varying(30) NOT NULL DEFAULT '',
                    "FailureReason"     character varying(500),
                    "Notes"             character varying(500),
                    "CreatedAt"         timestamp with time zone NOT NULL DEFAULT now(),
                    "UpdatedAt"         timestamp with time zone NOT NULL DEFAULT now(),
                    "PaidAt"            timestamp with time zone,
                    CONSTRAINT "PK_ExamOrders" PRIMARY KEY ("Id")
                );
                CREATE INDEX IF NOT EXISTS "IX_ExamOrders_StudentId"  ON "ExamOrders" ("StudentId");
                CREATE INDEX IF NOT EXISTS "IX_ExamOrders_ExamPageId" ON "ExamOrders" ("ExamPageId");
                CREATE INDEX IF NOT EXISTS "IX_ExamOrders_OfferId"    ON "ExamOrders" ("OfferId");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS exam_notifications (
                    id                uuid                   NOT NULL,
                    exam_id           uuid,
                    title             character varying(300) NOT NULL,
                    slug              character varying(320) NOT NULL,
                    content_html      text                   NOT NULL,
                    summary           character varying(500),
                    notification_type integer                NOT NULL DEFAULT 0,
                    important_dates   jsonb,
                    source_url        character varying(500) NOT NULL,
                    canonical_url     character varying(500),
                    meta_title        character varying(300),
                    meta_description  character varying(500),
                    published_at      timestamptz,
                    is_ai_processed   boolean  NOT NULL DEFAULT false,
                    ai_processed_at   timestamptz,
                    created_at        timestamptz NOT NULL,
                    updated_at        timestamptz NOT NULL,
                    status            integer NOT NULL DEFAULT 0,
                    CONSTRAINT "PK_exam_notifications" PRIMARY KEY (id)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ix_exam_notifications_slug         ON exam_notifications (slug);
                CREATE INDEX        IF NOT EXISTS ix_exam_notifications_exam_id      ON exam_notifications (exam_id);
                CREATE INDEX        IF NOT EXISTS ix_exam_notifications_is_ai_processed ON exam_notifications (is_ai_processed);
                CREATE INDEX        IF NOT EXISTS ix_exam_notifications_published_at ON exam_notifications (published_at);
                CREATE INDEX        IF NOT EXISTS ix_exam_notifications_status       ON exam_notifications (status);
                CREATE INDEX        IF NOT EXISTS ix_exam_notifications_type         ON exam_notifications (notification_type);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "ExamAccesses" (
                    "Id"         uuid    NOT NULL DEFAULT gen_random_uuid(),
                    "StudentId"  uuid    NOT NULL,
                    "ExamPageId" uuid    NOT NULL,
                    "OrderId"    uuid    NOT NULL,
                    "GrantedAt"  timestamp with time zone NOT NULL DEFAULT now(),
                    "ExpiresAt"  timestamp with time zone,
                    "IsActive"   boolean NOT NULL DEFAULT true,
                    CONSTRAINT "PK_ExamAccesses" PRIMARY KEY ("Id")
                );
                CREATE INDEX        IF NOT EXISTS "IX_ExamAccesses_StudentId"  ON "ExamAccesses" ("StudentId");
                CREATE INDEX        IF NOT EXISTS "IX_ExamAccesses_ExamPageId" ON "ExamAccesses" ("ExamPageId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_ExamAccesses_OrderId"    ON "ExamAccesses" ("OrderId");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "ExamOrderTransactions" (
                    "Id"                uuid                     NOT NULL DEFAULT gen_random_uuid(),
                    "ExamOrderId"       uuid                     NOT NULL,
                    "Event"             character varying(80)    NOT NULL DEFAULT '',
                    "RazorpayPaymentId" character varying(100),
                    "RazorpayOrderId"   character varying(100),
                    "Amount"            numeric,
                    "RawPayload"        text,
                    "CreatedAt"         timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "PK_ExamOrderTransactions" PRIMARY KEY ("Id")
                );
                CREATE INDEX IF NOT EXISTS "IX_ExamOrderTransactions_ExamOrderId" ON "ExamOrderTransactions" ("ExamOrderId");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS content_versions (
                    id                   uuid                  NOT NULL,
                    entity_type          character varying(80) NOT NULL,
                    entity_id            uuid                  NOT NULL,
                    content_html         text                  NOT NULL,
                    created_at           timestamptz           NOT NULL,
                    "ExamNotificationId" uuid,
                    CONSTRAINT "PK_content_versions" PRIMARY KEY (id)
                );
                ALTER TABLE content_versions
                    ADD COLUMN IF NOT EXISTS "ExamNotificationId" uuid;
                CREATE INDEX IF NOT EXISTS ix_content_versions_entity ON content_versions (entity_type, entity_id, created_at);
                CREATE INDEX IF NOT EXISTS "IX_content_versions_ExamNotificationId" ON content_versions ("ExamNotificationId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "content_hashes");
            migrationBuilder.DropTable(name: "content_versions");
            migrationBuilder.DropTable(name: "ExamAccesses");
            migrationBuilder.DropTable(name: "ExamOrderTransactions");
            migrationBuilder.DropTable(name: "test_questions");
            migrationBuilder.DropTable(name: "exam_notifications");
            migrationBuilder.DropTable(name: "ExamOrders");
            migrationBuilder.DropTable(name: "exams");
            migrationBuilder.DropTable(name: "ExamOffers");
        }
    }
}
